name             'commons'
maintainer       'Fabio G. Martins'
maintainer_email 'fabiogoma@gmail.com'
license          'Apache 2.0'
description      'Installs/Configures Commons'
long_description 'Installs/Configures Commons'
version          '0.1.0'
